"""EXPERIMENT, not a validated layout: real_001_rebuilt's own network,
unchanged (imported directly, never rebuilt or edited), with its Road
swapped for highway_env's own RegulatedRoad -- see
highway_env/road/regulation.py. Answers a narrow question: does replacing
the Road class alone change anything about how the layout renders?

WHY THIS SHOULD BE A NO-OP FOR RENDERING, ARGUED BEFORE BEING MEASURED:
RoadGraphics.display()/draw_routes()/draw_bg_lanes() (see display_all.py)
only ever read road.network and the route/lane-index lists this module
re-exposes below -- never road.__class__, and never road.vehicles (this
file adds none). RegulatedRoad's own added behavior (lane.priority-based
yielding, enforce_road_rules()) only ever runs from its own step(dt)
override, which a static render never calls. So a pixel-for-pixel
comparison against real_001_rebuilt's own render is a real test of that
claim, not just a formality -- see
layout/layouts/_compare_regulated_render.py for the actual comparison
(now covering all ten real_NNN layouts, each with its own
real_NNN_regulated_road.py sibling built the same way as this file).

WHY THIS FILE EXISTS SEPARATELY, NOT AS AN EDIT TO real_001_rebuilt.py:
that file is explicitly locked (own docstring: "do not edit this file",
chmod 444 on disk) -- exactly the "prototype in a new file first" rule its
own docstring names. Every geometry-defining name below is imported
directly from it, not reconstructed, so there is no second copy of the
network-building logic to drift out of sync.

NOT YET A CLAIM THAT RegulatedRoad IS A DROP-IN REPLACEMENT FOR THIS
CODEBASE'S OWN crossing_conflict_brake -- only that swapping the Road
class doesn't corrupt anything about the layout ITSELF. RegulatedRoad's
own priority-based yielding needs each lane's own `priority` set
meaningfully (build_scene.py's own primitives don't currently pass one,
so every lane here defaults to whatever highway_env.road.lane.LineType's
own default is), and its enforce_road_rules() would need to actually run
every tick (via RegulatedRoad.step(), not plain Road.step()) for that
behavior to do anything at all -- both open questions for a follow-up,
not answered by this file. watch.py's own --regulated flag (see its
_VisibleRegulatedRoad) already exercises the live-simulation side of
this, confirmed directly to fire (17 yield events in a 1500-step/100s
run) -- this file is specifically the static-render side of the question.
"""
from highway_env.road.regulation import RegulatedRoad

from real_001_rebuilt import (  # noqa: F401 -- re-exposed for any tooling that expects these names
    _build_network, _HUMAN_ROUTE_LANES, _ROBOT_ROUTE_LANES,
    HUMAN_ROUTE, ROBOT_ROUTE, route_adjacent_lane_indexes,
)


def build_road() -> RegulatedRoad:
    return RegulatedRoad(network=_build_network())
