"""
MISHA NEW CHANGE - exploratory/diagnostic only, not part of any pipeline.

Finds layouts where SteakLimitVisionHumanModel's DEDUCED SUBTASK (not just its
low-level action) genuinely differs depending on FOV. Earlier work showed
steak_island does NOT have this property (low-level actions diverge, subtask
sequence doesn't) - see diagnose_dynamic_fov.py and the conversation that led
to it.

Mechanism (grounded in agent.py):
  - SteakLimitVisionHumanModel.ml_action() (agent.py:1472) branches on
    self.knowledge_base['other_player'] (line 1488) to compute other_has_meat/
    other_has_onion/etc (1516-1521), which gate which subtask fires.
  - init_knowledge_base() (agent.py:757) copies 'other_player' and
    pot/chop/sink states from ground truth UNCONDITIONALLY - no FOV gating.
  - update() (agent.py:1231) is what actually gates 'other_player' tracking
    by in_bound() (agent.py:873) on subsequent calls - THIS is where FOV
    can make a shadow's belief diverge from ground truth.

Test pattern: build a "setup" state (arbitrary, ground truth, shared by all
shadows equally via init_knowledge_base), then a "reveal" state where the
ROBOT does exactly one thing (picks up meat) whose position relative to the
human is in_bound for some FOV candidates and not others. From there, each
FOV's shadow actually DRIVES ITS OWN forward simulation (robot stays put,
holding the meat) for N more steps, so we can see whether the subtask-level
divergence is a one-step blip or a persistent behavioral fork.

Also: writes the 3 validated layouts to fov/layouts/*.layout (real .layout
format, loadable via load_dict_from_file/from_grid) and renders a schematic
PNG per layout to fov/layouts/images/ showing the grid, both players, and the
human's FOV cone at 60/120/180 so it's visually obvious why divergence does
or doesn't happen.

Run with: python -m my_methods.bayesian.fov_subtask_divergence_test
"""
import os
import numpy as np

from overcooked_ai_py.mdp.overcooked_mdp import SteakHouseGridworld, Action
from overcooked_ai_py.mdp.overcooked_env import OvercookedEnv
from overcooked_ai_py.planning.planners import MediumLevelPlanner
from overcooked_ai_py.helpers import BASE_PARAMS
from overcooked_ai_py.agents.agent import SteakLimitVisionHumanModel

FOV_CANDIDATES = (60, 120, 180)
N_FORWARD_STEPS = 40

FOV_LAYOUTS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "fov", "layouts")
FOV_IMAGES_DIR = os.path.join(FOV_LAYOUTS_DIR, "images")

TERRAIN_COLORS = {
    'X': '#888888', 'O': '#e07b39', 'M': '#c0392b', 'D': '#3477a8',
    'P': '#7d3c98', 'B': '#27ae60', 'W': '#17a2b8', 'S': '#d4ac0d',
    ' ': '#f5f5f0',
}


def build_grid(width, height, features):
    rows = []
    for y in range(height):
        row = []
        for x in range(width):
            if x == 0 or x == width - 1 or y == 0 or y == height - 1:
                row.append('X')
            else:
                row.append(features.get((x, y), ' '))
        rows.append(''.join(row))
    return rows


def write_layout_file(name, grid, layout_params):
    os.makedirs(FOV_LAYOUTS_DIR, exist_ok=True)
    path = os.path.join(FOV_LAYOUTS_DIR, name + ".layout")
    # MISHA NEW CHANGE: don't clobber an existing file - build_mdp_and_mlp()
    # calls this unconditionally every time it's invoked (e.g. by any script
    # that later re-loads a layout by name), which was overwriting curated
    # .layout files' documenting comment headers with this generic one every
    # time they got reloaded for a new test.
    if os.path.exists(path):
        return path
    grid_str = "\n                ".join(grid)
    with open(path, "w") as f:
        f.write(
            "# MISHA NEW CHANGE - generated by my_methods/bayesian/fov_subtask_divergence_test.py\n"
            "# Verified to produce subtask-level (not just low-level action) FOV divergence\n"
            "# in SteakLimitVisionHumanModel - see fov/layouts/images/%s.png\n"
            "{\n"
            '    "grid":  """%s""",\n'
            '    "start_order_list": %s,\n'
            '    "cook_time": %d,\n'
            '    "delivery_reward": %d,\n'
            "    'num_items_for_steak': %d,\n"
            "    'chop_time': %d,\n"
            "    'wash_time': %d,\n"
            '    "rew_shaping_params": None\n'
            "}\n" % (
                name, grid_str, layout_params['start_order_list'],
                layout_params['cook_time'], layout_params['delivery_reward'],
                layout_params['num_items_for_steak'], layout_params['chop_time'],
                layout_params['wash_time'],
            )
        )
    return path


def build_mdp_and_mlp(name, grid, order_list=None, cook_time=15, chop_time=5, wash_time=5,
                       num_items_for_steak=1, delivery_reward=20):
    layout_params = {
        'start_order_list': order_list or ['steak', 'steak'], 'cook_time': cook_time,
        'delivery_reward': delivery_reward, 'num_items_for_steak': num_items_for_steak,
        'chop_time': chop_time, 'wash_time': wash_time,
    }
    write_layout_file(name, grid, layout_params)
    params = dict(layout_params)
    params['layout_name'] = name
    mdp = SteakHouseGridworld.from_grid(grid, base_layout_params=params)
    mlp = MediumLevelPlanner.from_pickle_or_compute(mdp, BASE_PARAMS, force_compute=False, info=False)
    return mdp, mlp


def render_layout_image(name, grid, human_pos, human_ori, robot_pos):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Wedge, Rectangle

    width, height = len(grid[0]), len(grid)
    fig, axes = plt.subplots(1, len(FOV_CANDIDATES), figsize=(5 * len(FOV_CANDIDATES), 5.5))
    for ax, fov in zip(axes, FOV_CANDIDATES):
        for y, row in enumerate(grid):
            for x, c in enumerate(row):
                ax.add_patch(Rectangle((x, y), 1, 1, facecolor=TERRAIN_COLORS.get(c, '#f5f5f0'),
                                        edgecolor='#cccccc', linewidth=0.5))
                if c not in (' ', 'X'):
                    ax.text(x + 0.5, y + 0.5, c, ha='center', va='center', fontsize=11, fontweight='bold', color='white')

        # FOV cone (south-facing, matches in_bound()'s geometry for orientation (0,1))
        hx, hy = human_pos
        half = fov / 2.0
        cone_len = max(width, height)
        # human faces south (0,1); with set_ylim(height,0) flipping the display,
        # data-space angle 90 (+y) is what actually draws "downward on screen"
        wedge = Wedge((hx + 0.5, hy + 0.5), cone_len, 90 - half, 90 + half,
                       color='#f1c40f', alpha=0.35, zorder=1)
        ax.add_patch(wedge)

        ax.plot(hx + 0.5, hy + 0.5, marker=(3, 0, 180), markersize=22, color='#2980b9', zorder=5)
        ax.text(hx + 0.5, hy - 0.35, 'H', ha='center', fontsize=10, fontweight='bold', color='#2980b9')

        rx, ry = robot_pos
        ax.plot(rx + 0.5, ry + 0.5, marker='o', markersize=16, color='#e74c3c', zorder=5,
                markeredgecolor='black')
        ax.text(rx + 0.5, ry - 0.35, 'R', ha='center', fontsize=10, fontweight='bold', color='#e74c3c')

        ax.set_xlim(0, width)
        ax.set_ylim(height, 0)
        ax.set_aspect('equal')
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title(f"human FOV = {fov} deg", fontsize=12)

    fig.suptitle(name, fontsize=14, fontweight='bold')
    fig.tight_layout()
    os.makedirs(FOV_IMAGES_DIR, exist_ok=True)
    out_path = os.path.join(FOV_IMAGES_DIR, name + ".png")
    fig.savefig(out_path, dpi=130)
    plt.close(fig)
    return out_path


def run_sustained_divergence_test(name, grid, robot_idx, robot_start_pos, hide_pos, mlp=None, mdp=None):
    """
    MISHA NEW CHANGE - fixes the self-correction problem seen in
    run_reveal_and_progression_test: there, the meat dispenser sat right next
    to the robot's resting spot, so the human's mistaken 'go get more meat'
    detour walked straight toward the robot and re-revealed it in 1 step.

    Here the robot grabs meat next to its OWN dispenser (wherever that is in
    the "main work cluster", far from hide_pos), then physically WALKS (via
    the real motion planner, not a state hack) to hide_pos - a position
    verified via in_bound() to be outside the human's FOV=60 cone but inside
    FOV=120/180, and spatially separated from the whole work cluster so nothing
    the human legitimately needs to do ever brings hide_pos into view.
    """
    if mdp is None or mlp is None:
        mdp, mlp = build_mdp_and_mlp(name, grid)
    human_idx = 1 - robot_idx

    env = OvercookedEnv.from_mdp(mdp, info_level=0, horizon=200)
    setup_state = env.state.deepcopy()
    human_pos = setup_state.players[human_idx].position
    human_ori = setup_state.players[human_idx].orientation

    # 1) robot grabs meat (assumes robot starts adjacent to M, facing it)
    joint = [Action.STAY, Action.STAY]
    joint[robot_idx] = Action.INTERACT
    env.step(tuple(joint))
    assert env.state.players[robot_idx].held_object is not None, "robot failed to pick up meat"

    # 2) robot walks to hide_pos (any orientation - only position matters for in_bound)
    goal = (hide_pos, (0, 1))
    cur_pos_and_or = env.state.players[robot_idx].pos_and_or
    assert mlp.mp.is_valid_motion_start_goal_pair(cur_pos_and_or, goal), \
        f"no valid path from {cur_pos_and_or} to {goal}"
    action_plan, _, _ = mlp.mp.get_plan(cur_pos_and_or, goal)
    for a in action_plan:
        joint = [Action.STAY, Action.STAY]
        joint[robot_idx] = a
        env.step(tuple(joint))

    reveal_state = env.state.deepcopy()
    robot_final_pos = reveal_state.players[robot_idx].position
    print(f"\n=== {name} (sustained) ===")
    print(f"human@{human_pos}/{human_ori}  robot walked {len(action_plan)} steps to hide_pos={hide_pos}, "
          f"actual final pos={robot_final_pos}  held={reveal_state.players[robot_idx].held_object}")

    img_path = render_layout_image(name, grid, human_pos, human_ori, robot_final_pos)
    print(f"  image -> {img_path}")

    progressions = {}
    for fov in FOV_CANDIDATES:
        shadow_env = OvercookedEnv.from_mdp(mdp, info_level=0, horizon=200)
        shadow_env.state = reveal_state.deepcopy()

        shadow = SteakLimitVisionHumanModel(mlp, setup_state, vision_limit=True, vision_bound=fov, debug=False)
        shadow.set_agent_index(human_idx)
        shadow.init_knowledge_base(setup_state)

        subtasks = []
        for t in range(N_FORWARD_STEPS):
            try:
                a_human, _ = shadow.action(shadow_env.state)
            except AssertionError:
                subtasks.append('STUCK')
                break
            subtasks.append(shadow.prev_chosen_subtask)
            joint = [Action.STAY, Action.STAY]
            joint[human_idx] = a_human
            shadow_env.step(tuple(joint))
        progressions[fov] = subtasks
        print(f"  FOV={fov:>3}: {subtasks}")

    seqs = {fov: tuple(seq) for fov, seq in progressions.items()}
    full_seq_diverges = len(set(seqs.values())) > 1
    # how many of the first N_FORWARD_STEPS entries differ from the FOV=180 (widest/most-informed) sequence?
    ref = seqs[180]
    disagreement_counts = {
        fov: sum(1 for a, b in zip(seq, ref) if a != b) for fov, seq in seqs.items()
    }
    print(f"  --> full-sequence divergence: {full_seq_diverges}  |  "
          f"steps disagreeing with FOV=180: {disagreement_counts}")
    return full_seq_diverges, progressions, disagreement_counts


def run_reveal_and_progression_test(name, grid, robot_idx):
    mdp, mlp = build_mdp_and_mlp(name, grid)
    human_idx = 1 - robot_idx

    base_env = OvercookedEnv.from_mdp(mdp, info_level=0, horizon=100)
    setup_state = base_env.state.deepcopy()

    joint_action = [Action.STAY, Action.STAY]
    joint_action[robot_idx] = Action.INTERACT
    base_env.step(tuple(joint_action))
    reveal_state = base_env.state.deepcopy()

    robot_pos = reveal_state.players[robot_idx].position
    human_pos = setup_state.players[human_idx].position
    human_ori = setup_state.players[human_idx].orientation

    print(f"\n=== {name} ===")
    print(f"human@{human_pos}/{human_ori}  robot reveal pos@{robot_pos} "
          f"held={reveal_state.players[robot_idx].held_object}")

    img_path = render_layout_image(name, grid, human_pos, human_ori, robot_pos)
    print(f"  image -> {img_path}")

    progressions = {}
    for fov in FOV_CANDIDATES:
        env = OvercookedEnv.from_mdp(mdp, info_level=0, horizon=100)
        env.state = reveal_state.deepcopy()

        shadow = SteakLimitVisionHumanModel(mlp, setup_state, vision_limit=True, vision_bound=fov, debug=False)
        shadow.set_agent_index(human_idx)
        shadow.init_knowledge_base(setup_state)

        subtasks = []
        for t in range(N_FORWARD_STEPS):
            try:
                a_human, _ = shadow.action(env.state)
            except AssertionError:
                subtasks.append('STUCK')
                break
            subtasks.append(shadow.prev_chosen_subtask)

            joint = [Action.STAY, Action.STAY]
            joint[human_idx] = a_human
            env.step(tuple(joint))
        progressions[fov] = subtasks
        print(f"  FOV={fov:>3}: {subtasks}")

    first_step = {fov: seq[0] for fov, seq in progressions.items()}
    diverges_at_all = len(set(tuple(s) for s in progressions.values())) > 1
    diverges_first_step_only = (len(set(first_step.values())) > 1) and not diverges_at_all
    full_seq_diverges = len(set(tuple(s) for s in progressions.values())) > 1

    print(f"  --> first-step divergence: {len(set(first_step.values())) > 1}  |  "
          f"full-sequence divergence: {full_seq_diverges}")
    return full_seq_diverges, progressions


def main():
    tests = []

    features1 = {
        (4, 5): '1', (7, 3): '2',
        (7, 6): 'B', (4, 6): 'M',
        (12, 1): 'O', (2, 1): 'D', (10, 1): 'P', (1, 7): 'W', (13, 7): 'S',
    }
    tests.append(("fov_meat_dx3_dy2", build_grid(15, 9, features1), 0))

    features2 = {
        (3, 4): '1', (7, 3): '2',
        (7, 6): 'B', (3, 5): 'M',
        (12, 1): 'O', (2, 1): 'D', (10, 1): 'P', (1, 7): 'W', (13, 7): 'S',
    }
    tests.append(("fov_meat_dx4_dy1", build_grid(15, 9, features2), 0))

    features3 = {
        (10, 5): '1', (7, 3): '2',
        (7, 6): 'B', (10, 6): 'M',
        (2, 1): 'O', (12, 1): 'D', (4, 1): 'P', (13, 7): 'W', (1, 7): 'S',
    }
    tests.append(("fov_meat_dx3_dy2_mirrored", build_grid(15, 9, features3), 0))

    # MISHA NEW CHANGE - sustained-divergence layout: station cluster kept far
    # (east side) from the robot's hiding spot (west side) so the human's
    # mistaken 'go get more meat' detour walks AWAY from the robot instead of
    # toward it, and can't self-correct by accidentally walking past it.
    human_pos = (10, 3)
    hide_pos = (7, 5)   # verified: FOV60=blind, FOV120/180=visible from human_pos facing south
    robot_start = (16, 3)
    sustained_features = {
        robot_start: '1', human_pos: '2',
        (16, 4): 'M',
        (18, 3): 'O', (13, 3): 'D', (18, 6): 'P', (13, 6): 'B', (18, 8): 'W', (13, 8): 'S',
    }
    sustained_grid = build_grid(20, 11, sustained_features)
    sustained_name = "fov_meat_sustained_far_cluster"

    passed_count = 0
    for name, grid, robot_idx in tests:
        try:
            passed, progressions = run_reveal_and_progression_test(name, grid, robot_idx)
            if passed:
                passed_count += 1
        except Exception as e:
            import traceback
            print(f"\n=== {name} ===\n  ERROR: {type(e).__name__}: {e}")
            traceback.print_exc()

    print(f"\n{passed_count}/{len(tests)} layouts show subtask-sequence FOV divergence "
          f"(over {N_FORWARD_STEPS} steps post-reveal)")

    try:
        run_sustained_divergence_test(sustained_name, sustained_grid, 0, robot_start, hide_pos)
    except Exception as e:
        import traceback
        print(f"\n=== {sustained_name} ===\n  ERROR: {type(e).__name__}: {e}")
        traceback.print_exc()


if __name__ == "__main__":
    main()
